### ISSUE TITLE
Updating With Docker Documentation

### ISSUE THREAD

**Issue by MagikEh** [nuxsmin/sysPass-doc#12]
[Updating to recent versions](https://github.com/sysPass/sysPass-doc/blob/3.1/docs/source/updating/v3.1.rst) using Docker is not well documented. 

Originally installed using the [docker compose method](https://github.com/sysPass/sysPass-doc/blob/3.1/docs/source/installing/docker.rst#docker-compose) and now that v3.1 is out I'm not sure on the approprate upgrade process for my situation. 

Can you provide more details pertaining to the update process for those of us that used the quick install methods?
 * Do we just download the new repo and relaunch the container?
 * Are the config/backup files properly volumed so we don't need to worry about copying them over?
 * Are there any potential pitfalls that we may encounter on the way to new versions?

Thanks for the awesome app!

**Comment by nuxsmin** [comment]
Hello, I agree that some parts of the documentation need to be refined. 

Talking about Docker, IMHO I think that someone who installs Docker and therefore installing apps on it, should have a slight knowledge about containers lifecycle and some best practices about how to deal with this kind of technology. This is so because, though I would have given a lot of documentation, some parts of the technology would remain unknown, thus it will lead to catastrophic issues...sorry if this is misunderstood, the whole idea is to be careful with new technology and keep documented as much as possible before using it :wink: 

That being said, if you are using docker-compose (the quick and fine way), you only need to perform a full database and app backups before upgrading (https://doc.syspass.org/en/3.1/application/backup.html), change the app's image tag within composer's YAML file, run docker-compose as if you were creating the environment (ie. `up -d`) and follow the steps on the web UI

Thanks for the feedback!

**Comment by MagikEh** [comment]
Thanks for the advice! I'll have to look more into Docker's best practices

I'm glad to see the update process is a simple one as well. As a side question, what is the feasability of giving sysPass the ability to do in place updates? So Users might only need to click a button in the admin account's UI?

**Comment by nuxsmin** [comment]
> what is the feasability of giving sysPass the ability to do in place updates? So Users might only need to click a button in the admin account's UI?

It's a good topic, and I'd like to implement it, but I needs a valuable effort an many people are already doing it by using Git (ie. cloning the git repo directly). An automated method will absolutely break the Docker philosophy, that is reproducible and scalable containers, because once you upgrade a container it will never be reproducible (think about Kubernetes) using common ways (not committing docker images...). So I think the current way is quite homogeneous across the different technologies used to run sysPass.

**Comment by nuxsmin** [comment]
Added some side notes on: https://doc.syspass.org/en/3.1/updating/strategies.html

:wink:

**Comment by MagikEh** [comment]
Haha, you're on fire! Thanks a million man!
